# Generated by Django 3.1.2 on 2020-11-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersblock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='McSkin',
            field=models.ImageField(default='defaultMcSkin.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ProfilePic',
            field=models.ImageField(default='defaultProfilePic.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='UserVerification',
            field=models.BooleanField(default='false'),
        ),
    ]
