# Generated by Django 3.1.2 on 2020-11-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersblock', '0003_auto_20201108_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='McSkin',
            field=models.ImageField(default='defaultMcSkin.jpg', upload_to='McSkins'),
        ),
    ]
