# Generated by Django 3.1.2 on 2020-11-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersblock', '0004_auto_20201108_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='UserVerification',
            field=models.BooleanField(default=False),
        ),
    ]
