# Generated by Django 3.1.2 on 2020-11-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersblock', '0006_auto_20201108_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='UserVerification',
            field=models.BooleanField(default=False),
        ),
    ]
