# Generated by Django 3.1.2 on 2020-11-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersblock', '0007_auto_20201108_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='UserVerification',
        ),
    ]
