# Generated by Django 3.1.2 on 2020-11-07 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersblock', '0008_remove_profile_userverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ProfilePic',
        ),
    ]
