# Generated by Django 3.1.2 on 2020-11-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersblock', '0009_remove_profile_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='McSkin',
        ),
        migrations.AddField(
            model_name='profile',
            name='UserVerification',
            field=models.BooleanField(default=False),
        ),
    ]
